#!/bin/bash

echo $# # количество параметров
echo $@ # массив параметров

if [ $# -lt 1 ]			# что за lt 1
then					# почему нельзя $# != 0 
	echo taco
	exit 1				# зачем этооо
fi

shift 2 				# это зачем?
